version: "3.8"
services:
  briefkasten-web:
    extends:
      file: docker-compose.yml
      service: briefkasten-web
    volumes:
      - type: bind
        source: ./apps/web
        target: /prod/web
        read_only: true
  briefkasten-backend:
    extends:
      file: docker-compose.yml
      service: briefkasten-backend
    volumes:
      - type: bind
        source: ./apps/backend
        target: /prod/backend
        read_only: true
